site_name: MLDocs
site_url: https://example.com/
theme:
  name: material
  custom_dir: overrides
  font:
    text: Open Sans
  features:
    - content.tabs.link
    - navigation.top
    - navigation.sections
    # - navigation.indexes
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Algorithms:
    - Linear Regression: algorithms/linear-regression/index.md
    - Gradient Descent: algorithms/gradient-descent.md
  - Definitions:
    - Deep Learning: definitions/index.md
  - Concepts:
    - Deep Learning Specialisation: concepts/dls-course-2.md
    - Overfitting/Underfitting: concepts/overfitting-underfitting.md
  - Equations:
    - Norms: equations/norms.md
  - Reinforcement Learning: 
    - reinforcement-learning/index.md
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
extra_javascript:
  - javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js