name: mldocs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prepare:
    if: |
      github.repository == 'harrybaines/mldocs' &&
      ((github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]'))
    outputs:
      ref: ${{ steps.ref.outputs.ref }}
    runs-on: ubuntu-20.04
    steps:
      - name: Set ref
        id: ref
        run: |
          GH_REF=""
          if [ '${{ github.event_name == 'pull_request_target' }}' = 'true' ]; then
            GH_REF="${{ github.event.pull_request.head.sha }}"
          fi
          echo "::set-output name=ref::${GH_REF}"
          
  deploy:
    needs: prepare
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ needs.prepare.outputs.ref }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.8"

      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - run: python3 -m pip install --upgrade pip pipenv
      - run: pipenv sync --dev
      - run: pipenv run mkdocs build --config-file ./mkdocs.yml
